version: '3.9'

services:

  lock-manager-api:
    build:
      context: ./projects/lock-manager-api
      dockerfile: Dockerfile
    ports:
      - '8181:8181'
    depends_on:
      - redis1
      - redis2
      - redis3
    environment:
      REDIS_ADDRESSES: "redis1:6379,redis2:6379,redis3:6379"
    networks:
      - redis-network

  redis1:
    image: redis:latest
    container_name: redis1
    ports:
      - "6379:6379"
    command: ["redis-server", "--port", "6379"]
    networks:
      - redis-network

  redis2:
    image: redis:latest
    container_name: redis2
    ports:
      - "6380:6379"
    command: ["redis-server", "--port", "6379"]
    networks:
      - redis-network

  redis3:
    image: redis:latest
    container_name: redis3
    ports:
      - "6381:6379"
    command: ["redis-server", "--port", "6379"]
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
